# Generated by Django 3.2.6 on 2021-12-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='total_experience',
        ),
    ]
